project:
  type: book

book:
  title: "Built-up Index Handbook"
  author: "Vanchy Li"
  date: today
  chapters:
    - index.qmd
    - 01-background.qmd
    - 02-ndbi.qmd
    - 03-ui-ibi-ndbai.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    toc: true
