# References {.unnumbered}


- Bouzekri, Sara, Abdel Aziz Lasbet, and Ammar Lachehab. “A New Spectral Index for Extraction of Built-Up Area Using Landsat-8 Data.” Journal of the Indian Society of Remote Sensing 43, no. 4 (2015): 867–73. https://doi.org/10.1007/s12524-015-0460-6.

- C. Jieli, L. Manchun, L. Yongxue, S. Chenglei and H. Wei, "Extract residential areas automatically by New Built-up Index," 2010 18th International Conference on Geoinformatics, Beijing, China, 2010, pp. 1-5, doi:10.1109/GEOINFORMATICS.2010.5567823. 

- Ettehadi Osgouei, Paria, Sinasi Kaya, Elif Sertel, and Ugur Alganci. “Separating Built-Up Areas from Bare Land in Mediterranean Cities Using Sentinel-2A Imagery.” Remote Sensing 11, no. 3 (2019): 345. https://doi.org/10.3390/rs11030345.

- He, Chunyang, Peijun Shi, Dingyong Xie, and Yuanyuan Zhao. 2010. “Improving the Normalized Difference Built-up Index to Map Urban Built-up Areas Using a Semiautomatic Segmentation Approach.” Remote Sensing Letters 1 (4): 213–21. https://doi.org/10.1080/01431161.2010.481681. 

- Kebede, Tsion Ayalew, Binyam Tesfaw Hailu, and Karuturi Venkata Suryabhagavan. “Evaluation of Spectral Built-up Indices for Impervious Surface Extraction Using Sentinel-2A MSI Imageries: A Case of Addis Ababa City, Ethiopia.” Environmental Challenges 8 (August 2022): 100568. https://doi.org/10.1016/j.envc.2022.100568.

- Pontius Jr, Robert Gilmore, and Kangping Si. 2014. “The Total Operating Characteristic to Measure Diagnostic Ability for Multiple Thresholds.” International Journal of Geographical Information Science 28 (3): 570–83. https://doi.org/10.1080/13658816.2013.862623. 

- Santra, Abhisek, Shreyashi Santra Mitra, Suman Sinha, and Shidharth Routh. “Performance Testing of Selected Spectral Indices in Automated Extraction of Impervious Built-up Surface Features Using Resourcesat LISS-III Image.” Arabian Journal of Geosciences 13, no. 22 (2020): 1229. https://doi.org/10.1007/s12517-020-06183-z. 

- Stathakis, Demetris, Konstantinos Perakis, and Igor Savin. “Efficient Segmentation of Urban Areas by the VIBI.” International Journal of Remote Sensing 33, no. 20 (2012): 6361–77. https://doi.org/10.1080/01431161.2012.687842. 

- Valdiviezo-N, Juan C., Alejandro Téllez-Quiñones, Adan Salazar-Garibay, and Alejandra A. López-Caloca. “Built-up Index Methods and Their Applications for Urban Extraction from Sentinel 2A Satellite Data: Discussion.” Journal of the Optical Society of America A 35, no. 1 (2018): 35. https://doi.org/10.1364/JOSAA.35.000035.

- Waqar, Mirza Muhammad, Johum Fatimah Mirza, Rafia Mumtaz, and Ejaz Hussain. "Development of new indices for extraction of built-up area & bare soil from landsat data." Open Access Sci. Rep 1, no. 1 (2012): 4.

- Xu, H. 2008. “A New Index for Delineating Built‐up Land Features in Satellite Imagery.” International Journal of Remote - Sensing 29 (14): 4269–76. https://doi.org/10.1080/01431160802039957. 

- Zha, Y., J. Gao, and S. Ni. 2003. “Use of Normalized Difference Built-up Index in Automatically Mapping Urban Areas from TM Imagery.” International Journal of Remote Sensing 24 (3): 583–94. https://doi.org/10.1080/01431160304987. 

- Zhou, Yi, Guang Yang, Shixin Wang, Litao Wang, Futao Wang, and Xiongfei Liu. “A New Index for Mapping Built-up and Bare Land Areas from Landsat-8 OLI Data.” Remote Sensing Letters 5, no. 10 (2014): 862–71. https://doi.org/10.1080/2150704X.2014.973996. 
